services:
  db:
    image: mysql:8.4.7
    container_name: recipe-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}    # 資料庫root密碼
      MYSQL_DATABASE: recipe_db                   # 資料庫名稱
      MYSQL_USER: ${DB_USERNAME}                  # 建立 arden_me 帳號
      MYSQL_PASSWORD: ${DB_PASSWORD}              # 設定 arden_me 的密碼
    ports:
      - "3307:3306"
    command: --mysql-native-password=ON
    volumes:
      - mysql_data:/var/lib/mysql  # 將資料庫檔案掛載到實體硬碟，確保重啟後食譜資料不會消失

  app:
    build: .
    container_name: recipe-springboot
    restart: always
    ports:
      - "8080:8080"
    environment:
      # 注意：強制告訴 Spring Boot，在 Docker 裡請用 prod 環境設定！
      SPRING_PROFILES_ACTIVE: prod
      # 注意：這裡的 URL 網址把原本的 localhost 改成了 db (也就是上面資料庫服務的名稱)
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/recipe_db?useSSL=false&serverTimezone=Asia/Taipei&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      # 食譜圖片在容器內的實體目錄
      APP_RECIPE_IMAGE_DIR: /app/images/recipes

    volumes:
      # 將容器內的圖片資料夾，掛載到實體主機的 ./images 資料夾，避免圖片遺失
      - ./images:/app/images
    depends_on:
      - db
    
volumes:
  mysql_data: